database_uri = "sqlite:////tmp/tmpne71olx1"

[ratelimit.read]
capacity = 200
consume = 1
refill = 10

[ratelimit.create]
capacity = 200
consume = 1
refill = 10

[ratelimit.delete]
capacity = 200
consume = 1
refill = 10
